name: Docker Image CI

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [graalvm11, adoptopenjdk11, spss]
        include:
          - name: graalvm11
            base: lustefaniak/graalvm:11-20.2.0-d09b66f38a61439502b9d82359565e079eb5bdeb
          - name: adoptopenjdk11
            base: adoptopenjdk/openjdk11:jdk-11.0.9_11-alpine-slim
            platform_deps: "apk add --no-cache alpine-baselayout bash"
          - name: spss
            base: adoptopenjdk/openjdk11:jdk-11.0.9_11-debian-slim
            platform_deps: "apt-get install bash"

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          echo docker build . --build-arg BASE_IMAGE="${{ matrix.base }}"  --build-arg PLATFORM_DEPS="${{ matrix.platform_deps }}" -t "lustefaniak/docker-gcp-java:${{ matrix.name }}_${{ github.sha }}"
          docker build . --build-arg BASE_IMAGE="${{ matrix.base }}"  --build-arg PLATFORM_DEPS="${{ matrix.platform_deps }}" -t "lustefaniak/docker-gcp-java:${{ matrix.name }}_${{ github.sha }}"
      - name: Test
        run: ./test.sh "lustefaniak/docker-gcp-java:${{ matrix.name }}_${{ github.sha }}"
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u lustefaniak --password-stdin
      - name: Push snapshot version
        run: docker push lustefaniak/docker-gcp-java:${{ matrix.name }}_${{ github.sha }}
      - name: Push from master
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker tag lustefaniak/docker-gcp-java:${{ matrix.name }}_${{ github.sha }} lustefaniak/docker-gcp-java:${{ matrix.name }}
            docker push lustefaniak/docker-gcp-java:${{ matrix.name }}
          else
            echo "Not master branch, skipping..."
          fi
