name: Docker Image CI

on:
  push:
    branches:
    - master
    tags:
    - v*
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker:
        - "NAME=alpine-graalvm8 BASE_IMAGE=lustefaniak/graalvm:8-20.1.0-9e005023e2ab26a7749441e7cbb7b7081a637ac2"
        - "NAME=alpine-graalvm11 BASE_IMAGE=lustefaniak/graalvm:11-20.1.0-9e005023e2ab26a7749441e7cbb7b7081a637ac2"
        - "NAME=alpine-adoptopenjdk8 BASE_IMAGE=adoptopenjdk/openjdk8:jre8u262-b10-alpine"
        - "NAME=alpine-adoptopenjdk11 BASE_IMAGE=adoptopenjdk/openjdk11:jre-11.0.8_10-alpine"
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ${{ matrix.docker }} VERSION=${{ github.sha }} ./build.sh
    - name: Test image
      run: ${{ matrix.docker }} VERSION=${{ github.sha }} ./test.sh
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u lustefaniak --password-stdin
    - name: Push from master
      run: |
        ${{ matrix.docker }} VERSION=${{ github.sha }} ./push_snapshot.sh
        if [ "${{ github.ref }}" = "refs/heads/master" ]; then
          ${{ matrix.docker }} VERSION=${{ github.sha }} ./push.sh
        else
          echo "Not master branch, will not update main images..."
        fi
